spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false

  flyway:
    baseline-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false